---
inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - bin/*
    - config/application.rb
    - config/environments/*
    - vendor/**/*
    - .vendor/**/*
