---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - bin/*
    - config/application.rb
    - config/environments/*
    - db/schema.rb
    - vendor/**/*
    - .vendor/**/*
Naming/PredicateName:
  ForbiddenPrefixes:
    - "is_"
    - "have_"
Rails/I18nLocaleTexts:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"
