---
inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - bin/*
    - config/application.rb
    - config/environments/*
    - vendor/**/*
    - .vendor/**/*
Naming/PredicateName:
  ForbiddenPrefixes:
    - "is_"
    - "have_"
Rails/I18nLocaleTexts:
  Enabled: false
