---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - bin/*
    - config/application.rb
    - config/environments/*
    - db/migrate/*active_storage.rb
    - db/schema.rb
    - vendor/**/*
    - .vendor/**/*

Naming/PredicatePrefix:
  ForbiddenPrefixes:
    - "is_"
    - "have_"

Rails/I18nLocaleTexts:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"
