name: test-build

on:
  - pull_request
  - push

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake rubocop
